### PR TITLE
feat(frontend): added helperText and custom validation function

### PR DESCRIPTION
**Pull request by antoniomuso**
I added the `helperText`.

### CODE REVIEW

**Comment by JellyBellyDev** [comment]
Maybe we should add also the documentation to configure the text?

**Comment by antoniomuso** [comment]
Yes, sure. I didn't add it because the other PR is in progress.

**Comment by simonecorsi** [comment]
Lgtm thanks!

**Review by simonecorsi — APPROVED** [review]
LGTM 🚀

**Pull request merged**
